import Head from "next/head";
import React, { ReactElement } from "react";
import Hero from "../components/home/Hero";
import Bottombar from "../components/ui/Bottombar";
import Footer from "../components/ui/Footer";
import Navbar from "../components/ui/Navbar";
import { ToastContainer } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";

type Props = { children: ReactElement };

function Root({ children }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer
        position="top-right"
        autoClose={2000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
      />
      <Navbar />
      <main className="pb-10">{children}</main>
      <Footer />
      <Bottombar />
    </>
  );
}

export default Root;
